<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-02T12:31:55 IST" name="Suite" finished-at="2024-07-02T12:32:04 IST" duration-ms="9341">
    <groups>
    </groups>
    <test started-at="2024-07-02T12:31:55 IST" name="Test" finished-at="2024-07-02T12:32:04 IST" duration-ms="9341">
      <class name="test.LandingPageTesting">
        <test-method is-config="true" signature="logReport()[pri:0, instance:test.LandingPageTesting@27406a17]" started-at="2024-07-02T12:31:55 IST" name="logReport" finished-at="2024-07-02T12:31:55 IST" duration-ms="194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logReport -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:test.LandingPageTesting@27406a17]" started-at="2024-07-02T12:31:55 IST" name="launchBrowser" finished-at="2024-07-02T12:32:00 IST" duration-ms="4736" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="selectPriceOfMobileFromTenThousandToTwentyThouandFromPriceFilterSlider()[pri:0, instance:test.LandingPageTesting@27406a17]" started-at="2024-07-02T12:32:00 IST" name="selectPriceOfMobileFromTenThousandToTwentyThouandFromPriceFilterSlider" finished-at="2024-07-02T12:32:03 IST" duration-ms="3707" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at test.LandingPageTesting.selectPriceOfMobileFromTenThousandToTwentyThouandFromPriceFilterSlider(LandingPageTesting.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectPriceOfMobileFromTenThousandToTwentyThouandFromPriceFilterSlider -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:test.LandingPageTesting@27406a17]" started-at="2024-07-02T12:32:04 IST" name="logResult" finished-at="2024-07-02T12:32:04 IST" duration-ms="291" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=selectPriceOfMobileFromTenThousandToTwentyThouandFromPriceFilterSlider status=FAILURE method=LandingPageTesting.selectPriceOfMobileFromTenThousandToTwentyThouandFromPriceFilterSlider()[pri:0, instance:test.LandingPageTesting@27406a17] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
        <test-method is-config="true" signature="clearData()[pri:0, instance:test.LandingPageTesting@27406a17]" started-at="2024-07-02T12:32:04 IST" name="clearData" finished-at="2024-07-02T12:32:04 IST" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearData -->
      </class> <!-- test.LandingPageTesting -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
